services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: timemanager_db
    environment:
      POSTGRES_USER: ${DB_USER:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-user}
      POSTGRES_DB: ${DB_NAME:-timemanager}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - timemanager_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: timemanager_backend
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3000}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-timemanager}
      DB_USER: ${DB_USER:-dev}
      DB_PASSWORD: ${DB_PASSWORD:-user}
      JWT_SECRET: ${JWT_SECRET:-CHANGE_THIS_SECRET_IN_PRODUCTION}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost}
      DB_SSL_ENABLED: ${DB_SSL_ENABLED:-false}
    expose:
      - "3000"
    depends_on:
      - postgres
    networks:
      - timemanager_network
    restart: unless-stopped

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost}
    container_name: timemanager_frontend
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - timemanager_network
    restart: unless-stopped

  # Reverse Proxy (Nginx)
  reverse-proxy:
    image: nginx:alpine
    container_name: timemanager_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - timemanager_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  timemanager_network:
    driver: bridge
